#!/bin/bash

BIN="./bin"

# ---------------------------------------------------------------------
CMD="qemu -m 64 -hda ./rootfs.msdos -cdrom ./os.iso -boot d"

echo $CMD
$($CMD)



# echo 'qemu-system-i386 ./os.iso'
# qemu-system-i386 ./os.iso


# ---------------------------------------------------------------------
# Linux/Multiboot boot specific:
# -kernel bzImage use 'bzImage' as kernel image
# -append cmdline use 'cmdline' as kernel command line
# -initrd file    use 'file' as initial ram disk
# -dtb    file    use 'file' as device tree image
# ---------------------------------------------------------------------
