#!/bin/bash

# ---------------------------------------------------------------------
echo 'qemu-system-i386 -cdrom ./os.iso'
qemu-system-i386 -m 64 -cdrom ./os.iso

# ---------------------------------------------------------------------
# Linux/Multiboot boot specific:
# -kernel bzImage use 'bzImage' as kernel image
# -append cmdline use 'cmdline' as kernel command line
# -initrd file    use 'file' as initial ram disk
# -dtb    file    use 'file' as device tree image
# ---------------------------------------------------------------------
