#!/bin/bash


rm -f boot.o kernel.o kernel.iso kernel.bin

as boot.s -o boot.o
gcc -c kernel.c -o kernel.o -std=gnu99 -ffreestanding -O2 -Wall -Wextra
gcc -T linker.ld -o kernel.bin -ffreestanding -O2 -nostdlib boot.o kernel.o -lgcc


#if grub-file --is-x86-multiboot kernel.bin; then
#    echo "multiboot confirmed"
#else
#    echo "the file is not multiboot"
#fi
